env:
  - name: DB_HOST
    valueFrom: secret_db_host
  - name: DB_NAME
    valueFrom: secret_db_name
  - name: DB_USER
    valueFrom: secret_db_user
  - name: DB_PASSWORD
    valueFrom: secret_db_password
